package GUI;

import javax.swing.*;

public class ForepersonPage {
    private JButton logoutButton;
    private JButton bookingRegistrationButton;
    private JButton searchButton;
    private JTextField searchbarTextField;
    private JButton selectButton;
    private JList list1;
    private JScrollBar scrollBar1;
    private JTextField textField1;
    private JTextField textField2;
    private JTextField textField3;
    private JTextField textField4;
    private JButton saveButton;
    private JComboBox comboBox1;
    private JButton selectButton1;
    private JTextField textField6;
    private JTextField textField5;
    private JTextField textField7;
    private JTextField textField8;
    private JTextField textField9;
    private JTextField textField10;
    private JButton saveButton1;
    private JComboBox comboBox2;
    private JButton addBookingButton;
    private JButton invoicesButton;
    private JTextField searcbarTextField;
    private JButton searchButton1;
    private JList list2;
    private JButton printButton;
    private JButton monitorJobProgressButton;
    private JButton confirmButton;
    private JTextField jobDescriptionTextField;
    private JList list3;
    private JList list4;
    private JButton orderPartsButton;
    private JTextField searchbarTextField1;
    private JButton searchButton2;
    private JList list5;
    private JButton orderButton;
    private JButton jobsButton;
    private JButton finishButton;
    private JButton addButton1;
    private JTextField operationSTextField;
    private JButton addButton;
    private JButton pickAMechanicButton;
    private JComboBox comboBox3;
    private JComboBox comboBox4;
    private JButton confirmButton1;
    private JButton changeReOrderThresholdButton;
    private JButton saveButton2;
    private JButton changePasswordButton;
    private JComboBox comboBox5;
    private JButton changeButton;
    private JButton searchButton3;
    private JButton alterCustomerDetailsButton;
    private JList list6;
    private JTextField textField11;
    private JTextField textField12;
    private JTextField textField13;
    private JTextField textField14;
    private JButton searchButton4;
    private JList list7;
    private JButton deleteButton;
}
