package GUI;

import javax.swing.*;

public class FranchiseePage {
    private JPanel panel1;
    private JButton logoutButton;
    private JTextField searchbarTextField;
    private JButton searchButton;
    private JList list1;
    private JScrollBar scrollBar1;
    private JComboBox comboBox1;
    private JButton changeCustomerTypeButton;
    private JButton reportsButton;
    private JList Reports;
    private JTextField searchbarTextField2;
    private JButton searchButton3;
    private JButton printButton1;
    private JComboBox comboBox2;
    private JButton generateButton;
    private JTextField enterFrequencyDaysTextField;
    private JButton changeButton;
    private JComboBox comboBox3;
    private JComboBox comboBox4;
    private JButton bookingRegistrationButton;
    private JButton selectButton;
    private JTextField textField1;
    private JTextField textField2;
    private JTextField textField3;
    private JTextField textField4;
    private JButton saveButton;
    private JButton selectButton1;
    private JTextField textField6;
    private JTextField textField5;
    private JTextField textField7;
    private JTextField textField8;
    private JTextField textField9;
    private JTextField textField10;
    private JButton saveButton1;
    private JButton addBookingButton;
    private JButton monitorJobProgressButton;
    private JButton confirmButton;
    private JTextField jobDescriptionTextField;
    private JList list3;
    private JList list4;
    private JButton orderPartsButton;
    private JTextField searchbarTextField1;
    private JButton searchButton2;
    private JList list5;
    private JButton orderButton;
    private JButton saveButton2;
    private JComboBox comboBox5;
    private JButton saveButton4;
    private JButton changePasswordButton;
    private JButton alterCustomerDetailsButton;
    private JList list6;
    private JTextField textField11;
    private JTextField textField12;
    private JTextField textField13;
    private JTextField textField14;
    private JButton searchButton4;
    private JList list7;
    private JButton deleteButton;
}
